apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: hello-world
    name: hello
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  resources:
    limits:
      cpu: 1
      memory: "1G"
    requests:
      cpu: 500m
      memory: "512M"
status: {}
