apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    api: hello-world
  name: hello
spec:
  containers:
  - image: hello-world
    name: hello
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
